name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ...
        run: |
          npm install -g @magidoc/cli@6.3.0
          which magidoc
          ls -l $(which magidoc)
